"""
SIA CLI Tooling — Phase 3.2
Provides rapid bootstrapping and configuration validation for the SIA Framework.
"""
import typer
import os
import shutil
from pathlib import Path
from rich.console import Console

app = typer.Typer(help="SIA Framework CLI Tool - EU AI Act Governance")
console = Console()

@app.command()
def init(
    industry: str = typer.Option(
        "general", help="Industry preset: general, healthcare, hr, finance"
    )
):
    """
    Initialize a new SIA governance configuration using an industry preset.
    """
    console.print(f"[bold blue]Initializing SIA Configuration for: {industry}[/bold blue]")
    
    # Locate blueprints
    pkg_dir = Path(__file__).resolve().parent.parent.parent.parent
    blueprints_dir = pkg_dir / "configs" / "blueprints"
    
    preset_file = f"{industry}_v1.yaml"
    if industry == "general":
        preset_file = "general_transparency.yaml"
    elif industry == "hr":
        preset_file = "hr_recruitment_v1.yaml"
        
    src_path = blueprints_dir / preset_file
    dest_path = Path("sia_logic_gate.yaml")
    
    if dest_path.exists():
        console.print("[yellow]Warning: sia_logic_gate.yaml already exists in current directory. Use --force to overwrite.[/yellow]")
        raise typer.Exit(1)
        
    if src_path.exists():
        shutil.copy(src_path, dest_path)
        console.print(f"[green]Successfully created sia_logic_gate.yaml from {preset_file}[/green]")
    else:
        # Generate a minimal default if blueprint not found
        console.print(f"[yellow]Blueprint {preset_file} not found. Creating a default config...[/yellow]")
        default_config = f"""# SIA Governance Configuration: {industry}
metadata:
  version: "1.0"
  description: "Generated by SIA CLI"
"""
        dest_path.write_text(default_config, encoding="utf-8")
        console.print("[green]Successfully created default sia_logic_gate.yaml[/green]")

@app.command()
def validate(config_path: str = typer.Argument("sia_logic_gate.yaml")):
    """
    Lint and validate a SIA governance configuration file.
    """
    path = Path(config_path)
    if not path.exists():
        console.print(f"[bold red]Error: Configuration file {config_path} not found.[/bold red]")
        raise typer.Exit(1)
        
    console.print(f"[bold blue]Validating {config_path}...[/bold blue]")
    # Basic linting logic (could be expanded)
    try:
        import yaml
        with open(path, "r", encoding="utf-8") as f:
            data = yaml.safe_load(f)
        
        if "metadata" not in data:
            console.print("[yellow]Warning: Missing 'metadata' block.[/yellow]")
            
        console.print("[green]Configuration syntax is valid.[/green]")
    except Exception as e:
        console.print(f"[bold red]Validation failed: {e}[/bold red]")
        raise typer.Exit(1)

if __name__ == "__main__":
    app()
